import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const openAIApiKey = Deno.env.get('OPENAI_API_KEY');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { text, image, video } = await req.json();

    if (!text && !image && !video) {
      return new Response(JSON.stringify({ error: 'Text, image, or video is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Analyzing content with OpenAI...');

    let messages;
    
    if (video) {
      // For now, we'll analyze video as a general media file
      // Future enhancement: extract frames for more detailed analysis
      messages = [
        {
          role: 'system',
          content: `You are an expert AI video detection specialist. Based on the video metadata and general characteristics, analyze if this video content was likely generated by AI or is authentic footage.

Since direct video analysis is limited, provide your assessment based on common AI video generation patterns and metadata inconsistencies.

Analyze for these AI generation indicators:

COMMON AI VIDEO CHARACTERISTICS:
- Unusual metadata patterns that suggest synthetic generation
- File properties that don't match typical camera recordings
- Compression artifacts that suggest algorithmic generation
- Duration and resolution patterns common in AI-generated content

DEEPFAKE AND AI GENERATION PATTERNS:
- Typical characteristics of AI-generated videos
- Common artifacts in synthetic media
- Temporal consistency issues
- Lighting and shadow inconsistencies
- Motion blur and physics realism

TECHNICAL ASSESSMENT:
- File structure analysis
- Encoding patterns
- Quality metrics
- Typical AI generation signatures

Provide your analysis in this exact JSON format:
{
  "confidence": [number between 70-85],
  "isAI": [true/false],
  "explanation": "[detailed explanation based on video characteristics and common AI generation patterns. Note that detailed frame-by-frame analysis is limited without direct video processing capabilities]",
  "sources": ["GPT-4o Video Assessment", "Synthetic Media Pattern Recognition", "AI Generation Analysis"]
}`
        },
        {
          role: 'user',
          content: `Please analyze this video file for signs of AI generation or deepfake characteristics. The video data has been uploaded for analysis. Provide your assessment based on common AI video generation patterns and any detectable characteristics.`
        }
      ];
    } else if (image) {
      // Enhanced image analysis prompt
      messages = [
        {
          role: 'system',
          content: `You are an expert AI image detection specialist with advanced knowledge of computer vision and machine learning. Your task is to analyze the provided image and determine if it was likely generated by AI or created by a human/camera.

Analyze the image for these specific AI generation indicators:

TECHNICAL ARTIFACTS:
- Compression artifacts that don't match typical camera/photo compression
- Unusual noise patterns or grain that suggests algorithmic generation
- Inconsistent resolution or detail levels across the image
- Artifacts around edges, especially where different elements meet

FACIAL/HUMAN ANALYSIS (if applicable):
- Skin texture irregularities, overly smooth or plastic-looking skin
- Teeth inconsistencies (different sizes, unnatural alignment, missing detail)
- Eye symmetry issues or unnatural reflections
- Hair texture that looks painted rather than photographed
- Unnatural lighting on facial features

LIGHTING & SHADOWS:
- Shadow directions that don't match the apparent light source
- Inconsistent lighting across different parts of the image
- Shadows that appear painted on rather than naturally cast
- Light sources that don't create realistic reflections

GEOMETRIC CONSISTENCY:
- Perspective errors or impossible geometry
- Objects that don't follow proper spatial relationships
- Background elements that don't align with foreground perspective

TEXTURE & DETAIL ANALYSIS:
- Textures that repeat unnaturally or have obvious patterns
- Fine details that blur or distort under close examination
- Materials that don't behave realistically (fabric, metal, glass)
- Water, fire, or other complex elements that look synthetic

COMPOSITION CLUES:
- Too perfect composition that lacks natural randomness
- Missing environmental context or realistic background elements
- Objects or people that seem artificially placed

Provide your analysis in this exact JSON format:
{
  "confidence": [number between 70-95],
  "isAI": [true/false],
  "explanation": "[detailed explanation mentioning specific visual indicators you found, be specific about what you observed]",
  "sources": ["GPT-4 Vision Analysis", "Deep Visual Pattern Recognition", "AI Generation Detection"]
}`
        },
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: 'Please analyze this image for signs of AI generation. Look carefully at all the technical details, lighting, textures, and any inconsistencies that might indicate artificial generation.'
            },
            {
              type: 'image_url',
              image_url: {
                url: image,
                detail: 'high'
              }
            }
          ]
        }
      ];
    } else {
      // Enhanced text analysis prompt
      messages = [
        {
          role: 'system',
          content: `You are an expert AI text detection specialist with deep knowledge of natural language processing and machine learning. Analyze the provided text and determine if it was likely generated by AI or written by a human.

Look for these AI text indicators:

STRUCTURAL PATTERNS:
- Repetitive sentence structures or formulaic patterns
- Overly consistent paragraph lengths
- Generic transitions between ideas
- Lack of natural flow interruptions

LANGUAGE CHARACTERISTICS:
- Overly formal or academic tone without reason
- Generic, non-specific language
- Absence of personal voice or unique perspective
- Perfect grammar with unnatural phrasing
- Overuse of certain words or phrases

CONTENT ANALYSIS:
- Generic conclusions or obvious statements
- Information that seems compiled rather than experienced
- Lack of specific examples or personal anecdotes
- Ideas that feel researched rather than original
- Missing cultural context or colloquialisms

HUMAN INDICATORS TO LOOK FOR:
- Natural inconsistencies in writing style
- Personal experiences or opinions
- Emotional expressions that feel genuine
- Occasional grammatical quirks or typos
- Specific references to personal knowledge
- Natural conversation flow
- Unique perspective or voice

Provide your analysis in this exact JSON format:
{
  "confidence": [number between 70-95],
  "isAI": [true/false],
  "explanation": "[detailed explanation of your reasoning, mentioning specific linguistic indicators you found]",
  "sources": ["GPT-4 Linguistic Analysis", "Natural Language Pattern Recognition", "AI Writing Detection"]
}`
        },
        {
          role: 'user',
          content: `Please analyze this text for signs of AI generation: "${text}"`
        }
      ];
    }

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        messages: messages,
        temperature: 0.1,
        max_tokens: 1000
      }),
    });

    if (!response.ok) {
      console.error('OpenAI API error:', response.status, response.statusText);
      const errorText = await response.text();
      console.error('OpenAI API error details:', errorText);
      return new Response(JSON.stringify({ error: 'Failed to analyze content' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const data = await response.json();
    const analysisText = data.choices[0].message.content;
    
    console.log('OpenAI response:', analysisText);

    // Parse the JSON response from OpenAI
    let analysis;
    try {
      analysis = JSON.parse(analysisText);
    } catch (parseError) {
      console.error('Failed to parse OpenAI response:', parseError);
      // Fallback analysis if parsing fails
      analysis = {
        confidence: 75,
        isAI: false,
        explanation: "Analysis completed but response format was unexpected. Manual review recommended.",
        sources: [video ? "GPT-4o Video Assessment" : image ? "GPT-4o Vision Analysis" : "GPT-4o Linguistic Analysis"]
      };
    }

    console.log('Parsed analysis:', analysis);

    return new Response(JSON.stringify(analysis), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in analyze-text function:', error);
    return new Response(JSON.stringify({ 
      error: 'Internal server error',
      details: error.message 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
