
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const openAIApiKey = Deno.env.get('OPENAI_API_KEY');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { text } = await req.json();

    if (!text) {
      return new Response(JSON.stringify({ error: 'Text is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Analyzing text with OpenAI...');

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: `You are an expert AI content detector. Analyze the provided text and determine if it was likely generated by AI or written by a human. 

Provide your analysis in this exact JSON format:
{
  "confidence": [number between 60-95],
  "isAI": [true/false],
  "explanation": "[detailed explanation of your reasoning, mentioning specific indicators you found]",
  "sources": ["GPT Analysis", "Pattern Recognition", "Linguistic Analysis"]
}

Look for these AI indicators:
- Repetitive sentence structures
- Overly formal or generic language
- Lack of personal voice or inconsistencies
- Perfect grammar with unnatural phrasing
- Generic conclusions or obvious statements
- Consistent tone without natural variation

Look for these human indicators:
- Natural flow and personal voice
- Occasional grammatical quirks or typos
- Specific personal experiences or opinions
- Natural inconsistencies in writing style
- Emotional expressions that feel genuine
- Cultural references or colloquialisms`
          },
          {
            role: 'user',
            content: text
          }
        ],
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      console.error('OpenAI API error:', response.status, response.statusText);
      return new Response(JSON.stringify({ error: 'Failed to analyze text' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const data = await response.json();
    const analysisText = data.choices[0].message.content;
    
    console.log('OpenAI response:', analysisText);

    // Parse the JSON response from OpenAI
    let analysis;
    try {
      analysis = JSON.parse(analysisText);
    } catch (parseError) {
      console.error('Failed to parse OpenAI response:', parseError);
      // Fallback analysis if parsing fails
      analysis = {
        confidence: 75,
        isAI: false,
        explanation: "Analysis completed but response format was unexpected. Manual review recommended.",
        sources: ["GPT Analysis"]
      };
    }

    console.log('Parsed analysis:', analysis);

    return new Response(JSON.stringify(analysis), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in analyze-text function:', error);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
