// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npfzbupioxhfdnutfqoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZnpidXBpb3hoZmRudXRmcW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDU3MDQsImV4cCI6MjA2NTQyMTcwNH0.gZzWAHCvNfvycYdC70mUw7ZcHvx0EwF7lT2G0o5MTyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);